## Fishery-Dependent Data

### Commercial
#### Landings
In Oregon, historical commercial landings from 1892 to 1986 were provided by ODFW (Karnowski et al. 2014).  Historical landings were consistent but minimal (< 1 mt) until the mid-1960s, except for a period from the mid-1930s to the late 1940s, during which landings increased to a high of 2.8 mt and declined again to under one mt.  From 1965 to 1986, landings averaged 6.6 mt annually.  Primary gear types during this historical period included longline and troll gears. However, ODFW commercial samplers suggest that these troll landings were primarily landed on hook and line gear, but not separated by gear type on the fish tickets (pers. comm. M. Freeman, ODFW). 

Landings from 1987 – 1999 were compiled from a combination of PacFIN, the central repository for West coast commercial landings (extracted on 11/17/2020), and a separate ODFW reconstruction that delineated species-specific landings in the unspecified categories on PacFIN (e.g. URCK and POP1, ODFW 2017). Vermilion rockfish landings from this reconstruction were substituted for the URCK and POP1 landings available from PacFIN, and added to PacFIN landings from other categories for a complete time series during this time period. Commercial landings from 2000 – 2020 are available on PacFIN (extracted on 11/17/2020 and 02/18/2021). Vermilion rockfish is one of several rockfish species landed by a nearshore, primarily live-fish fixed gear fishery centered on Oregon’s southern coast. Following the development of this nearshore commercial fishery in the late 1990s, ODFW implemented a state-permitted limited access fishery that regulated fleet size, period landing limits and established harvest guidelines (Rodomsky et al. 2020). Vermilion rockfish are landed almost exclusively with hook and line and bottom longline gear. On average, 99.8% of vermilion rockfish landings are from these two gear types (2000 – 2020). Landings from all other gear types, including fish pot and trawl, are minimal relative to jig and longline gears and sporadic. Commercial landings peaked in 1993 at 13.9 mt before declining and fluctuating between 1.5 and 4.8 mt (2000 – 2020). Landings in 2020 were 3.3 mt. 

Discards
So I can’t remember what we did with commercial discards…!  

#### Lengths
Commercial vermilion rockfish length samples are available from PacFIN from 1999 – 2020 (n = 2,355).  These samples were extracted on 02/24/2021.  Approximately 47.9% of these samples are females (n = 1,129) and 51.9% are males (n = 1,222). Only four fish were unsexed. The majority (93.3%) are from the southern Oregon coast, centered in Port Orford (67.4%) and Gold Beach (25.8%), where the majority of permit holders for the commercial nearshore fishery are based and where most of the landings are made.  The majority of length samples are from vermilion rockfish landed to the fresh (dead) market (93.5%).  Additionally, special projects length samples collected from the commercial fishery are available from PacFIN from 2000 - 2006, 2008 - 2009, and 2012 (n = 381; extracted on 02/24/2021). Special projects samples were not included in the length compositions used in this model. Table X shows sample size by year and fleet. 

#### Ages
There were 896 commercial age samples available from 2004 and 2007 - 2020. Approximately, 50.1% of samples were males (n = 449) and 49.9% were females (n = 447).  As with the length samples, the vast majority of samples are from the southern Oregon coast (95.8%, n = 858), including Port Orford (73.4%) and Gold Beach (22.3%). 


### Recreational
#### Removals
##### Historic Ocean Boat Landings (1979 – 2000)
Recently, the Oregon Department of Fish and Wildlife (ODFW) undertook an effort to comprehensively reconstruct all marine fish recreational ocean boat landings prior to 2001 (pers. comm. A. Whitman, ODFW).  Reconstructed catch estimates from the Oregon Recreational Boat Survey (ORBS) improve upon estimates from the federal Marine Recreational Fisheries Statistical Survey (MRFSS), which have known biases related to effort estimation and sampling (Van Voorhees et al. 2000) that resulted in catch estimates considered implausible by ODFW.  However, the ORBS sample estimates are known to lack the comprehensive spatial and temporal coverage of MRFSS.  Addressing this coverage issue is a major part of this reconstruction. In general, the base data and methodology for these reconstructed estimates are consistent with recent assessments for other nearshore species (Dick et al. 2016; Dick et al. 2018; Haltuch et al. 2018; Cope et al. 2019). 

Prior to 2001, ORBS monitored marine species in both multi-species categories, such as rockfish, flatfish, and other miscellaneous fishes, and as individual species, such as lingcod or halibut.  For this comprehensive reconstruction, four species categories were selected to reconstruct, including rockfish, lingcod, flatfish and miscellaneous, which constitute the bulk of the managed marine fish species.  Vermilion rockfish are a component of the rockfish species category.  

Category-level estimates were expanded to account for gaps in sampling coverage in two separate pathways. First, estimates from five major ports were expanded to include unsampled winter months in years lacking complete coverage.  Expansions were based on available year-round sampling data and excluded years where regulations may have impacted the temporal distribution of catch.  Second, all other minor port estimates were expanded to include seasonal estimates in years lacking any sampling based on the amount of minor port catch as compared to all major port estimates.  A subset of landings were sampled by ORBS for species compositions within these categories.  Once category-level landings were comprehensive in space and time, species compositions were applied for the three multi-species categories, including rockfish, flatfish and miscellaneous fish.  Borrowing rules for species compositions were specific to the category and determined based on a series of regression tree analyses that detailed the importance of each domain (year, month, port and fishing mode) to variability in compositions. 

Ocean boat estimates from 1979 – 2000 in numbers of fish of vermilion rockfish from the above described methods were converted to biomass using biological samples from MRFSS (pers. comm. A. Whitman, ODFW).  MRFSS biological data are available from 1980 – 1989 and 1993 – 2000. An annual average weight was applied to the total annual number of fish to obtain an annual landings estimate. Several years missing biological data (1979, 1990 – 1992) were filled in using neighboring years or interpolation. These landings in biomass were provided by ODFW and do not include an estimate of discards.  In order to account for historical discards, 6% was added to landings from 1979 – 2000.  This discard mortality estimate is an average of the annual discard mortality from 2001 – 2020 available on RecFIN.  Landings during this time period gradually increase to a peak of 13.0 mt in 1993 and fluctuate between four and six mt following that peak.

##### Modern Ocean Boat Landings (2001 – 2020)
Recreational landings for ocean boat modes from 2001 – 2020 are available from RecFIN.  Both retained and released estimates of mortality are included, though retained mortality contributes the vast majority to total mortality.  Release mortality is estimated from angler-reported release rates and the application of discard mortality rates from the PFMC.  From 2001 – 2020, landings averaged 5.8 mt, ranging from 3.2 to 9.3 mt. In 2020, ocean boat landings were 8.9 mt.

##### Shore and Estuary Landings (1980 – 2020)
The ODFW does not currently sample shore and estuary boat fishing trips, and in recent assessments, ODFW has provided reconstructed species-specific estimates of shore and estuary landings from 1980 – 2020 (Berger et al. 2015, Dick et al. 2018, Cope et al. 2019). When investigating shore and estuary data for this species, there were virtually no records of shore and estuary landings of vermilion rockfish, and so these were not included for this assessment. 

#### Lengths
Recreational length samples were obtained from three sources: MRFSS, RecFIN (ORBS) and ODFW special project sampling.  From 1980 – 1989 and from 1993 – 2000, the MRFSS program collected samples from ocean areas only (n = 403).  ODFW provided MRFSS samples with the addition of a column that flagged length values imputed from weights to allow for selection of directly measured values; however, sample size was limited and therefore, imputed lengths were used.  From 1980 – 1989, total lengths (mm) were collected by MRFSS, which were converted to fork length.  From 1993 – 2000, fork length (mm) was collected.  Length samples from 2001 – 2020 from the ORBS sampling program are available on RecFIN (n =11,081).  All ORBS samples are by fork length (mm).  All samples are from ocean trips. Special projects samples collected by ODFW staff from the recreational fishery are provided from 1998 – 2001 (n = 54) but were not used in the length compositions for the assessment model.  Table X details sample sizes by year and fleet.  

#### Ages
There were 1,196 recreational age samples available from 2005 – 2020 (Table X). Approximately, 45.8% of samples were males (n = 548) and 53.9% were females (n = 645).  There were three unsexed samples (0.25%). As with the length samples, the vast majority of samples are from the southern Oregon coast (93.3%, n = 1,116), primarily from Charleston (24.1%), Gold Beach (19.3%), Bandon (18.4%), and Brookings (18.0%). 

### Index of Abundance
#### Oregon ORBS Dockside Index (2001-2020)

Trip-level catch-per-unit-effort data from ORBS dockside sampling was obtained from ODFW on 04/15/2021. To mitigate the confounding of hourly effort associated with these trips with travel, the travel time was subtracted from the hours fished. Travel time was stratified by boat type (charter and private) and was calculated as boat type-specific speeds (13 mph for charter boat trips and 18 mph for private boat trips) multiplied by twice the distance between the port of origin and the reef that was fished. CPUE, expressed in terms of fish per angler-hour, was calculated by multiplying the number of anglers and the adjusted travel time. The database contains information on catch by species (number of retained fish), effort (angler hours), sample location (port where data were collected), date, bag limits, boat type (charter or private), and trip type (e.g., bottom associated fish).

##### ORBS CPUE Data Preparation, Filtering, and Sample Sizes
In order to define effective fishing effort for Vermilion (i.e. identify trips that were likely to catch the species), the method of Stephens and MacCall (2004) was used to predict the probability of catching a Vermilion given the occurrence of other species in the catch. The unfiltered data set contained 411,528 trips.  Multiple standardized filters are applied to ORBS trip-level data in order to remove outliers and data unsuitable for an index. These filters include trips with incorrect interview times, which impact calculation of effort, unreasonably long or short trips, and retaining bottomfish target trips. There were 117,042 trips available for the application of the Stephens-MacCall filter (Table XX). Species that are rarely encountered will provide little information about the likelihood of catching Vermilion, and so 47 “indicator” species that were caught in at least 30 Oregon trips (Figure XX). Catch of these commonly-encountered species in a given trip was coded as presence/absence (1/0) and treated as a categorical variable in the Stephens-MacCall logistic regression analysis.

The top six species with a high probability of co-occurrence with Vermilion include Other Rockfish, Olive Rockfish, Copper Rockfish, Quillback Rockfish, Lingcod and China Rockfish, all of which are commonly associated with rocky reef and kelp habitats in nearshore waters. The top six species were all strongly associated with Vermilion (significantly different from zero at the alpha = 0.05 level). The six species with the lowest probability of co-occurrence were Buffalo Sculpin, Butter Sole, Greenstriped Rockfish, Striped Seaperch, Jack Mackerel, and Sand Sole. These species are not commonly caught during the same trip as Vermilion, presumably due to different habitat associations and fishing techniques. The Area Under the Characteristics curve (AUC) for this model is 0.7931; Figure XX), a significant improvement over a random classifier (AUC = 0.5). AUC represents the probability that a randomly chosen observation of presence would be assigned a higher ranked prediction than a randomly chosen observation of absence. Stephens-MacCall proposed filtering (excluding) trips from the index standardization based on a criterion of balancing the number of false positives (FP) and false negatives (FN). The FN trips were retained, assuming that catching a Vermilion indicates that a nonnegligible fraction of the fishing effort occurred in habitat where the species occurs. Only “true negatives” (the 103,762 trips that neither caught a Vermilion, nor were predicted to catch them by the model) were excluded from the index standardization.

After filtering for species composition, further filters were explored for fishing closures and catches exceeding bag limits, but these were not needed.  The final dataset also excluded data from several ports with extremely small sample sizes and finally, trips that met criteria for irrational effort reporting (i.e., implausible values) or extreme catch rates (Table XX). 

##### ORBS CPUE Standardization: Model Selection, Fits, and Diagnostics
Data at the port level were sparse for all months and years, so trips to north and south ‘subregions’ and to season (a compilation of winter and summer months) in order to facilitate data categories conducive to exploring interactions between subregion and year. Vermilion are somewhat rarely encountered by the recreational fleet. In order to focus any signal coming from this index, the above filtered dataset was further refined by retaining only trips that occurred in the southern megaregion, where the majority of the recreational and commercial catch occurs, and during the summer months (May – September; Figure XX). Raw catch rate data suggested that trends in CPUE over time diverged substantially by subregion. Further, ports in the south coast generally have difficult bars in the winter, restricting most of the recreational effort to summertime. 
A delta-Generalized Linear Model (GLM) approach was used to model CPUE. Apart from differences in catch rate among month, and year, we also considered changes associated with boat type (charter and private; Figure XX), the bag limit for Vermilion rockfish, and the depths available to the recreational fleet for fishing. The binomial component for catch occurrence was modeled using a logit link function while the log of positive CPUE was modeled with a Gaussian distribution and an identity link function. Based on the Akaike Information Criterion (AIC), the binomial model selected as the best predictor of ORBS catch rates included year, boat type, and the open depths available to fishing (Table XX). Residuals from the binomial component of the delta-model are not expected to be normally distributed, so quantile residuals (Dunn and Smyth 1996) were simulated using the R package DHARMa. Effective sample sizes prevented the direct comparison of the model predicted values to the standardized residuals (Figure X, right panel); however, examination of the QQ plot residuals and the results of tests for outliers and differing distributions indicated no significant issues (Figure XX, left panel), indicating that despite a small sample size, the model approximated the data reasonably well. The positive model selected, again based on AIC, included year, boat type, month and an interaction term with year: boat type (Table XX). Again, effective sample sizes prevented the comparison of model predicted values to the standardized residuals (Figure X, right panel) but no other significant issues were identified (Figure XX, left panel). Given that only a single subregion was included in this model selection procedure, an area-weighted model was not utilized for Vermilion, as has been used for other nearshore species in recent assessments, such as cabezon (Cope et al. 2019) or blue rockfish (Dick et al. 2018).  

To estimate the uncertainty in the final index of abundance, it is necessary to account for the correlation structure between parameters within the binomial and lognormal components of the model, as well as with the combined (binomial and lognormal components) delta-model. The rstanarm package in R was used to replicate the best models using diffuse prior distributions that replicated point estimates from the maximum likelihood fits. The advantage of this approach is that the calculation of the index (summing relevant model parameters and combining model components) can be applied to posterior draws, preserving the correlation structure and propagating uncertainty into the final index (Figure XX; Table XX). As an additional diagnostic, replicate data sets were generated from the posterior predictive distribution, and compared the maximum likelihood estimates from the model components to the median estimates from the posterior distribution. As expected, the model closely matches the distribution from replicate data (Figure XX).
