## Reference Model Diagnostics and Results

### Model convergence and acceptability

While there is no definitive measure of model convergence, several measures are routinely applied. These criteria include a low maximum gradient (`r model$maximum_gradient_component`), inversion of the Hessian (passed), reasonable parameter values (passed), and acceptable fits to data (passed). 

An extra effort was given to ensure the model did not rest on a local likelihood minimum. This was done by starting the minimization process from dispersed parameter values away from the maximum likelihood estimates to determine if the approach found a better model fit (i.e., minimum negative log-likelihood value). Starting parameters used a jitter shift value of 0.1. This was repeated 100 times with 92 out of 100 runs returned to the reference model likelihood (Figure \ref{fig:jitter_01}). Another exploration using a jitter shift at 0.2 was used, but it returned 94 out of 100 runs equal to the reference model. A better fit, lower negative log-likelihood model was not found in any of these runs. The model did not experience convergence issues when provided reasonable starting values. Through the jittering and likelihood profiles, the present reference model represents the best fit to the data given the assumptions made. 


#### Fits to the Data
##### Lengths
Fits to the length data are examined based on the Pearson residuals-at-length, the annual mean lengths, and aggregated length composition data for the commercial and recreational fleets. Annual length composition fits are shown in [Appendix A](#app_a). Lengths are generally sampled better in the recreational fishery and after year 2000.

Pearson residuals of fits to the commerical fishery length data are generally low with no distinct pattern of misfitting despite lower sample sizes (Figure \ref{fig:com-rec-pearson}). Fits to the commercial fishery mean lengths, assuming Francis data-weighting, show increasing female and males lengths until after 2009, after which mean lengths are relatively stable, with a small drop in size in the most recent year (Figure \ref{fig:com-mean-len-fit}).  

Pearson residuals of fits to the combined sex recreational fishery length data are also generally low, though with small bands of misfitting (Figure \ref{fig:com-rec-pearson}). These small bands are not deemed concerning given the small residuals and that recruitments are estimated. Fits to the recreational fishery mean lengths, assuming Francis data-weighting, show a very similar trend as the commercial mean lengths, with increasing lengths until after 2009, after which mean lengths are relatively stable, with a drop in size in the most recent year (Figure \ref{fig:rec-mean-len-fit}).  

Aggregate fits by fleet are shown in Figure \ref{fig:agg-len-fit}.  The model fits the aggregate lengths for the sexed commerical fishery fleet and unsexed recreational female length data well. The commerical fishery data are fit less well given the smaller sample sizes. 


##### Conditional Age at Length
Fits to the conditioanl age at length data are examined based on the age-at-length Pearson residuals, the annual mean ages, and mean age at length by year for the commercial and recreational fleet samples. The maximum size of the Pearson residuals for both fleets was large (maximum = 30.56 and 30.63 for commercial and recretaional samples, respectively; [Appendix B](#app_b)), due to the inclusion of very small but aged as older fish. Most of the residuals were small and unnoteworthy and demonstrate the expected shape of the growth curve. As with the lengths, the mean age by year increased then leveled off, though the recreational mean ages continue to increase in the most recent years (Figures \ref{fig:com-mean-caal} and \ref{fig:rec-mean-caal}). The mean age for commercial stocks were generally around 15 years old, whereas the recretional ages are around 18 years old. Fits to the mean ages by length bins show acceptable fits consistent with model expectations [Appendix C](#app_c).
 

##### ORBS Survey Index of Abundance
The fit to the ORBS recreational survey index are generally good and consistent with other model sources as the trend shows a population increasing in the early 2000s then leveling off and dropping over recent years (Figure \ref{fig:orbs-index-fit}). The decreasing trend is more consistent over the last decade than indicated in the lengths or ages. Inital variance for the survey is extremely small, though it only took a small about of added variance to fit the index (`r round(model$parameters[grep("Q_extraSD_Recreational",model$parameters$Label),]$Value, 2)`). The catchability coefficient (q) `r round(exp(model$parameters[model$parameters$Label == "LnQ_base_Recreational(2)", 3]), 3)` was analytically solved for and very small relative to the total an absoute measure (q=1), a typical result of a fishery-based abundance index.


### Selectivity


### Reference Model Outputs 
#### Parameter Estimates
A total of sixteen primary parameters were estimated, along with sixty recruitment deviations. The reference model parameter estimates along with asymptotic standard errors are shown in Table \ref{tab:model-param} and the likelihood components are shown in Table \ref{tab:likes}. Estimates of derived reference points and approximate 95 percent asymptotic confidence intervals are provided in Table \ref{tab:referenceES}. 

The natural mortality for females and males was estimated at `r round(model$parameters[model$parameters$Label == "NatM_p_1_Fem_GP_1", 3])` and `r round(model$parameters[model$parameters$Label == "NatM_p_1_Mal_GP_1", 3],3)` yr^-1^, respectively. These values are below the mean prior value, but not unrreasonable given the corresponding longevities would be between 67 and 75 year old and the sampled max ages of 68 come from a fished population.

The estimates of sex-specific growth parameters were different from the externally estimated starting values (Table \ref{tab:params} and Figure \ref{fig:mod-est-len-age}). The estimated $k$ for female and male fish were greater than the values estimated externally using only available survey data (`r round(model$parameters[model$parameters$Label == "VonBert_K_Fem_GP_1", 3],3)`  for females and `r round(model$parameters[model$parameters$Label == "VonBert_K_Fem_GP_1", 3]*exp(model$parameters[model$parameters$Label == "VonBert_K_Mal_GP_1", 3]),3)` yr^-1^ for males).  The majority of female and male `r spp` growth occurs at younger ages, reaching near maximum length by age 20-25, depending upon sex, with female `r spp` reaching  larger maximum lengths (Figure \ref{fig:mod-est-len-age}). 

The estimated logistic selectivity curves for the commericial and recreational fishery look plausible (i.e., as a model convergence check for realism, the selectivity curves are not overtly outrageous) for each fishery and are very similar to each other (Figure \ref{fig:fleet_selectivity}). Selectivity at 50% maturity (commercial = `r round(model$parameters[model$parameters$Label == "Size_DblN_peak_Commercial(1)", 3],3)`cm; recreational = `r round(model$parameters[model$parameters$Label == "Size_DblN_peak_Recreational(2)", 3],3)`cm) was between the length at 50% (39.4cm) and 95% maturity (48cm). Future assessments could opt for parsimony and combine these two fisheries into one combined selectivity, though the model had no issue adding two more parameters given the available length data.

The time series of estimated recruitments and annual recruitment deviations are shown in Figures \ref{fig:recruits} and \ref{fig:rec-devs}. Years with the highest recruitment deviations were estimated to have occurred in 1993-1994, 1998, 2005, and 2015. The variance check on the recruitment deviations indicates well informed recruitments from 1980 to 2015, providing justifation for the estimation of recruitment. Recruitment deviations after 2015 are relatively uninformed with estimated deviations near zero where recruitment is estimated primarily based on the spawner-recruit curve (Figure \ref{fig:bh-curve}). The recruitment bias adjustment applied within the model across years is shown in Figure \ref{fig:bias-adj}.


#### Population Trajectory

The predicted spawning output (in millions of eggs) is provided in Table \ref{tab:timeseries} and plotted in Figure \ref{fig:ssb}. Estimated spawning output shows a large decline starting in the 1970s, with a continued decline into the late 1990s. This tracks the time period of major removals, though removals have stayed somewhat elevated since. Strong recruitments in the 1990s  The estimate of total biomass over time, which tracks that of spawning output, is shown in Figure \ref{fig:tot-bio}.

Relative spawning output declined below the management target ($SB_{40\%}$) in the early 1980s and again fell below the target starting in 2019 (Figure \ref{fig:depl}). The relative stock status at the start of `r endyr + 1` is estimated to be below the rockfish relative biomass target of 40 percent (`r round(model$derived_quants[model$derived_quants$Label == 'Bratio_2021','Value'], 2)`) but above the management threshold of 25 percent. Uncertainty intervals indicate the population never goes below the management limit ($SB_{25\%}$) and is near the target after a very low catch in 2020 (likely attributable to the COVID-19 pandemic). The very low catches in 2020 allowed the population to rebound under the assumption of determnistic recruitment.   

Recruitment was treated as deterministic (Figure \ref{fig:bh-curve}) and the overall yearly age-0 numbers declined slightly over time (Figure \ref{fig:recruits}). 


#### Reference Points

Reference points were calculated using the estimated fishery selectivity and removals in the most recent year of the model (`r endyr`, Table \ref{tab:referenceES}). Sustainable total yields  were `r round(model$derived_quants[model$derived_quants$Label == 'Dead_Catch_SPR', 'Value'], 2)` mt when using an $SPR_{50\%}$ reference harvest rate. The spawning output equivalent to 40 percent of the unfished spawning output ($SB_{40\%}$) was `r round(model$derived_quants[model$derived_quants$Label == 'SSB_SPR', 'Value'], 2)` millions of eggs. 

The `r endyr + 1` spawning output relative to unfished equilibrium spawning output is below the `r spp` relative biomass target of 40 percent but greater that the management limit of 25 percent (Figure \ref{fig:depl}). The fishing intensity, $1-SPR$, was above the harvest rate limit ($SPR_{50\%}$) between the 1970s and early 1980s, below the target for much of the time from the mid-1980s to early 2010s, and most of the recent several years have exceeded the target (Table \ref{tab:timeseries} and Figure \ref{fig:1-spr}). Table \ref{tab:referenceES} shows the full suite of estimated reference points for the base model and Figure \ref{fig:yield} shows the equilibrium curve based on a steepness value fixed at `r round(model$parameters[model$parameters$Label == "SR_BH_steep","Value"], 2)`.
