\clearpage

# Appendix A: Detailed Fit to Length Composition Data 

```{r, results='asis'}
plot_info = read.csv(file.path(mod_loc, "plots", "plotinfotable_for_doc.csv"))
len_fit = plot_info[which(plot_info$category == "LenComp"), ]
plot.vec = grep("comp_lenfit_flt", len_fit$label)
filein = file.path(mod_loc, "plots")

for (a in plot.vec){
	cap = len_fit$caption[a]
	lab = len_fit$label[a]
	add_figure(filein = file.path(filein, len_fit$file[a]), 
			   caption = cap, 
			   label = lab)
}

```

\clearpage

# Appendix B: Detailed Fit to Conditional-Age-at-Length Composition Data {#detailed-caal}

```{r, results='asis'}
plot_info = read.csv(file.path(mod_loc, "plots", "plotinfotable_for_doc.csv"))
len_fit = plot_info[which(plot_info$category == "A@LComp"), ]
plot.vec = c(grep("comp_condAALfit_residsflt1mkt0", len_fit$label),
			 grep("comp_condAALfit_residsflt2mkt0", len_fit$label))
find = sort(len_fit$label[plot.vec], index.return = TRUE)$ix
plot.vec = plot.vec[find[2:length(find)]]
filein = file.path(mod_loc, "plots")

for (a in plot.vec){
	cap = len_fit$caption[a]
	lab = len_fit$label[a]
	add_figure(filein = file.path(filein, len_fit$file[a]), 
			   caption = cap, 
			   label = lab)
}

```

\clearpage

# Appendix C: Detailed Fit to Conditional-Age-at-Length Composition Data {#detailed-caal}

```{r, results='asis'}
plot_info = read.csv(file.path(mod_loc, "plots", "plotinfotable_for_doc.csv"))
len_fit = plot_info[which(plot_info$category == "A@LComp"), ]
plot.vec = c(grep("comp_condAALfit_residsflt1mkt0", len_fit$label),
			 grep("comp_condAALfit_residsflt2mkt0", len_fit$label))
find = sort(len_fit$label[plot.vec], index.return = TRUE)$ix
plot.vec = plot.vec[find[2:length(find)]]
filein = file.path(mod_loc, "plots")

for (a in plot.vec){
	cap = len_fit$caption[a]
	lab = len_fit$label[a]
	add_figure(filein = file.path(filein, len_fit$file[a]), 
			   caption = cap, 
			   label = lab)
}

```
